[김태윤] 3주차 Binary_Search_And_Linked_List
AlgorithmReview-Organization-2/CodingReviewRepository pull request #214
Opened 2023-07-21 16:34 UTC by lala9663

## 문제 링크

- #203 
	~~- [268. Missing Number (EASY)](https://leetcode.com/problems/missing-number/)~~
	~~- [876. Middle of the Linked List (EASY)](https://leetcode.com/problems/middle-of-the-linked-list/)~~
- #208
	- [[실버 2] 랜선 자르기](https://www.acmicpc.net/problem/1654) 
	- [[실버 3] 예산](https://www.acmicpc.net/problem/2512)
- #204 
	- [1351. Count Negative Numbers in a Sorted Matrix (Easy)](https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/) 
	- [234. Palindrome Linked List (Easy)](https://leetcode.com/problems/palindrome-linked-list/)
- #207 
	- [[실버 4] 수 찾기](https://www.acmicpc.net/problem/1920) 
	- [[실버 4] 숫자 카드 2](https://www.acmicpc.net/problem/10816)
- #209
	- [2529. Maximum Count of Positive Integer and Negative Integer (Easy)](https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer/)
	- [206. Reverse Linked List (Easy)](https://leetcode.com/problems/reverse-linked-list/) 
- #212
	- [7795 실버III 먹을 것인가 먹힐 것인가
](https://www.acmicpc.net/problem/7795)
	- [1406 실버II 에디터](https://www.acmicpc.net/problem/1406)

2023-07-22 13:48 UTC, 724thomas requested changes
[268. Missing Number (EASY)](https://leetcode.com/problems/missing-number/)
문제 다시 풀어보길! 시간복잡도는 O(logN)이 나와야 정상

2023-07-22 13:48 UTC, 724thomas commented on Coding_0718 Binary_Search_And_Linked_List/최원준/김태윤/1번.md
> +```
이거는 이분탐색이 아님!
유튜브로 검색 한번 하고 다시 풀길..

2023-07-25 16:05 UTC, hoonii2 approved these changes

2023-07-25 16:05 UTC, hoonii2 commented on Coding_0718 Binary_Search_And_Linked_List/이강훈/김태윤/1번.md
> +```
이분탐색 굿~

2023-07-25 16:05 UTC, hoonii2 commented on Coding_0718 Binary_Search_And_Linked_List/이강훈/김태윤/2번.md
> +```
깔끔~~!

2023-07-25 16:08 UTC, hoonii2 commented on Coding_0718 Binary_Search_And_Linked_List/이강훈/김태윤/2번.md
> +        Arrays.sort(arr);
밑에서 사용할 때 배열 전체 반복해서 하나하나 비교해서
요건 불필요해보여~

2023-07-25 16:13 UTC, hoonii2 commented on Coding_0718 Binary_Search_And_Linked_List/이강훈/김태윤/2번.md
> +        long right = arr[N - 1];
right 값 구할 때 정렬해서 큰 거 찾는거보다 arr 배열에 입력 값 저장하는 for 문 돌 때 
max 값 계산하게하면 정렬 따로 안하고 어차피 필요한 O(N) 걸리는거 안에 해결 가능해보여

2023-07-26 06:58 UTC, JeYeongR approved these changes

2023-07-26 06:58 UTC, JeYeongR commented on Coding_0718 Binary_Search_And_Linked_List/류제영/김태윤/2번.md
> +        HashMap<Integer, Integer> map = new HashMap<>();
Map으로 풀 수 있네요.. 이 방법말고 이분 탐색으로 하면 시간 초과 안 뜰거에요!

2023-07-26 08:45 UTC, HongGuma approved these changes

2023-07-26 08:45 UTC, HongGuma commented on Coding_0718 Binary_Search_And_Linked_List/홍수희/김태윤/1번.md
> +4. 메모: 그냥 품..
ㅋㅋㅋㅋㅋㅋ 그래도 풀었다는데에 의의를 둡시다! 1차 목표는 답이 나오는것으로~! 그렇게 연습하는거에여

2023-07-26 08:45 UTC, HongGuma commented on Coding_0718 Binary_Search_And_Linked_List/홍수희/김태윤/2번.md
> +3. 자료구조: stack
stack 쓴것도 굿~

2023-07-26 09:15 UTC, flimberkim approved these changes

2023-07-26 09:15 UTC, flimberkim commented on Coding_0718 Binary_Search_And_Linked_List/김우석/김태윤/1번.md
> +        }
굿! 이것도 좋은 풀이인데, 이분탐색으로 푸는게 O(logN)이라 더 빠르다는점~!!

2023-07-26 09:15 UTC, flimberkim commented on Coding_0718 Binary_Search_And_Linked_List/김우석/김태윤/2번.md
> +        }
굿굿 👍

2023-07-26 16:00 UTC, lala9663 commented on Coding_0718 Binary_Search_And_Linked_List/이강훈/김태윤/2번.md
> +        Arrays.sort(arr);
인정 정렬하고나서 왜했지 생각했습니다;

2023-07-27 15:08 UTC, merged