[이강훈] 4주차 Tree_And_Tries
AlgorithmReview-Organization-2/CodingReviewRepository pull request #225
Opened 2023-07-27 09:16 UTC by hoonii2

- #216 
- #217 
- #218

2023-07-29 11:37 UTC, 724thomas requested changes

2023-07-29 11:37 UTC, 724thomas commented on Coding_0725 Tree_And_Tries/최원준/이강훈/1번.java
> +}
dfs로 풀긴하였으나, 잘 이해하고 있는지 모르겠다 ㅋㅋ

if (root==null) return;
....

으로 코드를 한번 짜보자

2023-07-29 11:37 UTC, 724thomas commented on Coding_0725 Tree_And_Tries/최원준/이강훈/2번.java
> +    }
이 부분도
if (root==null) return; 를 시작으로 하는 dfs 코드를 다시 한번 짜보자

2023-07-29 13:04 UTC, hoonii2 commented on Coding_0725 Tree_And_Tries/최원준/이강훈/1번.java
> +}
그건 l, r 없는 경우도 재귀 한번 더 되는거라 생각해서 if 문으로 조건 검사한건데 이게 비용이 더 클 것 같긴하네

형이 말한게 코드도 더 깔끔해지긴 할 거 같다,, 시도해볼게

2023-07-30 08:36 UTC, hoonii2 commented on Coding_0725 Tree_And_Tries/최원준/이강훈/2번.java
> +    }
변경 완료~ 깔끔하고 메모리도 덜 차지한다 땡큐!

2023-07-30 14:59 UTC, 724thomas approved these changes

2023-07-30 14:59 UTC, 724thomas commented on Coding_0725 Tree_And_Tries/최원준/이강훈/2번.java
> +    }
굳 잘했어~
메모리때문에 그런건 아니고, 나중에 다른 조건들이 붙으면 더 복잡해지는데, 이 구조를 외우고 있으면 수월하게 풀 수 있어서 그래

2023-07-30 14:59 UTC, 724thomas commented on Coding_0725 Tree_And_Tries/최원준/이강훈/1번.java
> +}
굳굳 잘풀었다~

2023-07-31 05:30 UTC, HongGuma approved these changes

2023-07-31 05:30 UTC, HongGuma commented on Coding_0725 Tree_And_Tries/홍수희/이강훈/2번.java
> +    public static int dfs(int index, int count){
오 재귀함수 굿~~

2023-07-31 05:30 UTC, HongGuma commented on Coding_0725 Tree_And_Tries/홍수희/이강훈/1번.java
> +0 1 , 0 2 , 0 3 도 정답 아닌가
정답 되는데 백준에서는 이진트리를 원했나봐

2023-07-31 15:41 UTC, smallsnail-study commented on Coding_0725 Tree_And_Tries/곽윤희/이강훈/1번.java
> +
굿굿 근데 Objects로 굳이 받은 이유가 있어?

2023-07-31 15:42 UTC, smallsnail-study commented on Coding_0725 Tree_And_Tries/곽윤희/이강훈/2번.java
> +    }
나랑 같은 코드 👍

2023-07-31 15:45 UTC, smallsnail-study approved these changes
코드 확인 완료 💯

2023-08-01 09:00 UTC, JeYeongR approved these changes

2023-08-01 09:00 UTC, JeYeongR commented on Coding_0725 Tree_And_Tries/류제영/이강훈/2번.java
> +        list.remove(0);
get()없이 바로 remove()으로 가능

2023-08-01 09:00 UTC, JeYeongR commented on Coding_0725 Tree_And_Tries/류제영/이강훈/2번.java
> +        list.remove(0);
풀이는 완벽..

2023-08-01 13:14 UTC, hoonii2 commented on Coding_0725 Tree_And_Tries/곽윤희/이강훈/1번.java
> +
전 항상 Null 체크를 Objects.isNull 로 하고있어요!

2023-08-01 13:18 UTC, hoonii2 commented on Coding_0725 Tree_And_Tries/류제영/이강훈/2번.java
> +        list.remove(0);
오 remove index 넣으면 value 반환해주는구나
역시 제영;;

2023-08-03 00:37 UTC, flimberkim approved these changes
굿 잘 풀었네

2023-08-07 06:37 UTC, merged